name: 'Create PR Checklist'
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  statuses: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create pending statuses
        uses: actions/github-script@v6
        with:
          script: |
            const checklist = [
              { key: "tests", context: "Run tests" },
              { key: "review", context: "Code review approved" },
              { key: "deploy", context: "Deploy to production" },
            ];
            for (const item of checklist) {
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.payload.pull_request.head.sha,
                state: 'pending',
                context: item.context,
                description: 'Awaiting manual approval via checklist',
              });
            }
      - name: Create PR checklist comment
        uses: wadackel/checkbox-workflow-action@v1
        with:
          id: pr-checklist
          number: ${{ github.event.pull_request.number }}
          config: |
            [
              {"tests": "Run tests"},
              {"review": "Code review approved"},
              {"deploy": "Deploy to production"}
            ]
          message: |
            ## PR Checklist
            {{body}}
